name: Generate Snake

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Snake
      uses: Platane/snk@v2
      with:
        github_user_name: AndiAhmaz
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Push Snake
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
